function uiHelpFeatures()
  cecho("\n<yellow>======================================================================")
  cecho("\n<green>"..centerText("ErionMud UI Features"))
  cecho("\n<yellow>======================================================================")
  cecho("\n\n<yellow>----------------------------------------------------------------------")
  cecho("\n<cyan> Features")
  cecho("\n<yellow>----------------------------------------------------------------------")
  cecho("\n<yellow>This UI is packed with features!")
  cecho("\n<yellow>")
  cecho("\n<cyan>  * <yellow>Selectable UI themes! (check out '<cyan>uitheme<yellow>')")
  cecho("\n<cyan>  * <yellow>Clickable 'VOTE on TMC' link")
  cecho("\n<cyan>  * <yellow>Chats and notices in the right console.")
  cecho("\n<cyan>  * <yellow>Character stats in the left console (with commas!).")
  cecho("\n<cyan>  * <yellow>Class list with active target class marker.")
  cecho("\n<cyan>  * <yellow>Main class and target class levels.")
  cecho("\n<cyan>  * <yellow>MUD Events in the top console.")
  cecho("\n<cyan>  * <yellow>Active events and timers in the left console.")
  cecho("\n<cyan>  * <yellow>Active quest info in the top console.")
  cecho("\n<cyan>  * <yellow>Quest bonus timer visible beside the quest timer.")
  cecho("\n<cyan>  * <yellow>Full ANSI map with area info and exits in the left console.")
  cecho("\n<cyan>  * <yellow>Vitals bars and details in the bottom console.")
  cecho("\n<cyan>  * <yellow>Active Target and pet info in the bottom console.")
  cecho("\n<yellow>")
  cecho("\n<yellow>[<cyan>Possible works in Progress<yellow>]")
  cecho("\n<red>  * <yellow>Active debuffs in the bottom console. (TODO)")
  cecho("\n<red>  * <yellow>Clickable Exits (from Caelinus's github) (TODO)")
  cecho("\n<red>  * <yellow>A Cortheus-proof bleu cheese filter! (Eh, it's a long shot)")
  echo("\n")
  cecho("\n<yellow>======================================================================\n")
end