function uiHelpCommands()
  cecho("\n<yellow>======================================================================")
  cecho("\n<green>"..centerText("ErionMud UI Commands"))
  cecho("\n<yellow>======================================================================")
  echo("\n")
  cecho("\n<cyan>uiclear <top|right><yellow> - Clears the entered console.")
  cecho("\n<cyan>uilock <all|left|top|right|bottom><yellow> - Locks the entered container.")
  cecho("\n<cyan>uiunlock <all|left|top|right|bottom><yellow> - Unlocks the entered container.")
  cecho("\n<cyan>uisave<yellow> - Saves all adjustable container states (as 'custom1').")
  cecho("\n<cyan>uiload<yellow> - Loads all adjustable container states (as 'custom1').")
  cecho("\n<cyan>uireset<yellow> - Reset all UI containers to their default states.")
  echo("\n")
  cecho("\n<cyan>rtq<yellow> - After starting a quest, use this command to 'runto' this area.")
  echo("\n")
  cecho("\n<yellow>======================================================================")
end
