-- Functions to build the left UI
-- The layout is:
-- - A main container at 100% of the needed space.
-- - A main label for applying stylesheets to the container. 
--   - This should be slightly smaller than the main container.
-- - MiniConsoles inside the main label as needed.
--   - These should be slightly smaller than the main label.